### ISSUE TITLE
Example not working in Safari

### ISSUE THREAD

**Issue by rothsandro** [viljamis/vue-design-system#65] opened 2018-04-05 12:29 UTC
The [example](https://vueds.com/example/) is not working in Safari 10.0.3 on OS X 10.11.6:

```
SyntaxError: Cannot declare a let variable twice: 'e'.
```

**Comment by viljamis** [comment] 2018-04-06 15:24
@rothsandro Thanks for reporting this! The development environment (including that example documentation) only supports the latest version of Safari (see https://github.com/viljamis/vue-design-system/wiki/frequently-asked-questions-(FAQ)#what-browsers-are-supported for browser support), and I’m guessing that is related to Safari 10’s bug with let variables: https://caniuse.com/#feat=let

I will see if there’s an easy way to fix this though as 10 isn’t that old.

**Comment by viljamis** [comment] 2018-04-25 06:00
@rothsandro I think this is related to: https://github.com/vue-styleguidist/vue-styleguidist/issues/83

**Comment by rothsandro** [comment] 2018-04-25 10:32
Yes, seems to be related. The last time I used Vue Styleguidist, the production build was not working in Safari.

**Comment by viljamis** [comment] 2018-05-30 16:13
Looking into this now and hoping it will get fixed in https://github.com/viljamis/vue-design-system/pull/82

**Comment by viljamis** [comment] 2018-05-31 12:38
@rothsandro looks like it’s working now. I do get a warning in console which is caused by something in Styleguidist, but at least everything’s working and it’s completely usable.

**Comment by viljamis** [comment] 2018-05-31 12:38
(I haven’t published this fix yet though)

**Comment by viljamis** [comment] 2018-05-31 13:54
Released in https://github.com/viljamis/vue-design-system/releases/tag/3.0.0

**Closed by viljamis** 2018-05-31 13:54 UTC
Labels: bug, roadmap, work-in-progress
