### ISSUE TITLE
A couple of broken links in the example

### ISSUE THREAD

**Issue by SolderHQ** [viljamis/vue-design-system#40] opened 2018-03-19 13:53 UTC
Hi,

I spotted a couple of broken links on the [example site](https://vueds.com/example/). Both on the [Index](https://vueds.com/example/#index) and [NotFound](https://vueds.com/example/#notfound) sections the link `Style Guide` points to `localhost:6060`.

![vue-ds-link](https://user-images.githubusercontent.com/17155971/37599504-995bdf24-2b8d-11e8-8f6c-e17bc3979ace.png)

Not a big thing, but wanted to let you know! :)

**Comment by viljamis** [comment] 2018-03-19 15:22
Thanks for letting me know! 👌

**Comment by viljamis** [comment] 2018-03-20 05:04
@SolderHQ I will close this for now since this is the expected behaviour (the component examples are showing whatever URLs are used inside the actual components)

**Closed by viljamis** 2018-03-20 05:04 UTC
